name: "uptime"

services:
  api:
    build: ./apps/API
    ports:
      - "3001:3001"
    env_file:
      - ./apps/API/docker.env
    depends_on:
      - postgres
      - redis
      - redis_streams

  consumer:
    build: ./apps/consumer-redis
    env_file:
      - ./apps/consumer-redis/docker.env
    depends_on:
      - redis
      - redis_streams

  db:
    build: ./apps/database
    env_file:
      - ./apps/database/docker.env
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  frontend:
    build: ./apps/frontend
    env_file:
      - ./apps/frontend/.env.local
    ports:
      - "3000:3000"
    depends_on:
      - api

  pusher:
    build: ./apps/pusher
    env_file:
      - ./apps/pusher/docker.env

  redis_streams:
    build: ./apps/redisstreams
    env_file:
      - ./apps/redisstreams/docker.env
    ports:
      - "4001:4001"

  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"

  postgres:
    image: timescale/timescaledb:latest-pg17
    environment:
      POSTGRES_DB: uptime
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: saklani2004*
    ports:
      - "5432:5432"
    volumes:
      - /media/shivamsaklani/Development/dockerdb:/var/lib/postgresql/data
